### ISSUE TITLE
Driver Fails to Install on Windows 8.1

### ISSUE THREAD

**Issue by rei-vilo** [Seeed-Studio/Signed_USB_Serial_Driver#1]
The driver fails to install on Windows 8.1. 
Unfortunately, Windows doesn't provide much information about the error.

**Comment by rei-vilo** [comment]
Despite being labelled as `signed`, the driver requires rebooting Windows 8.1 in special unprotected mode to install it. Please update the procedure accordingly.

**Comment by KillingJacky** [comment]
The sign of the driver seems problematic, already contacting the sign provider, please wait a few days (will ping you here if solved) or you can temporarily install it with Windows setting to unprotected mode. We're very sorry for the inconvenience.

**Comment by KillingJacky** [comment]
Hi @rei-vilo , the driver has been updated. We have resigned it.

**Comment by ZinggJM** [comment]
I tried to install on Windows 10 Home, Version 1703 64 bit on x64, and installation fails without any clue.

**Comment by rei-vilo** [comment]
Try rebooting Windows 10 in special unprotected mode to install the USB driver.

**Comment by ZinggJM** [comment]
I definitely will NOT do this with my working notebook. Throw the Seeeduino into a corner or to the back of a drawer.

**Comment by ZinggJM** [comment]
The reason seems to be that the ATmega16u2 came un-programmed.
I need to know which hex file to use for Seeeduino V4.2, because download fails with the hex file for Arduino/Genuino UNO.

**Comment by KillingJacky** [comment]
@ZinggJM Here's the firmware for the Atmega16u2 chip https://github.com/SeeedDocument/SeeeduinoV4/blob/master/resources/Arduino-usbserial-seeeduino-v4.zip
