### ISSUE TITLE
Improperly Signed

### ISSUE THREAD

**Issue by Saijin-Naib** [Seeed-Studio/Signed_USB_Serial_Driver#2]
The hash for the file is not present in the specified catalog file. The file is likely corrupt or the victim of tampering.
![image](https://user-images.githubusercontent.com/19295950/74209917-b9b90e80-4c57-11ea-9373-e34833156183.png)
Downloaded:  
https://github.com/Seeed-Studio/Signed_USB_Serial_Driver/releases/tag/1.0.1

```
Name: seeed_usb_serial.cat
Size: 17065 bytes (16 KiB)
SHA256: A4FEAD28DE22C075387BDC136F46A4FAE2DEAB014DE4809B723608DC08E9CB17
```

```
Name: seeed_usb_serial.inf
Size: 10545 bytes (10 KiB)
SHA256: A5D725415898C668D512433155759AF3B3423CFFE3CB2C737941689FF9356DAD
```

**Comment by LynnL4** [comment]
Please try to use the [driver](https://github.com/Seeed-Studio/Signed_USB_Serial_Driver/releases/download/1.0.2/Signed_USB_Serial_Driver-1.0.2.zip) of the [released-1.0.2](https://github.com/Seeed-Studio/Signed_USB_Serial_Driver/releases/tag/1.0.2)
