### ISSUE TITLE
Not able to install Drivers on Windows 8.1

### ISSUE THREAD

**Issue by aryehassbian** [Seeed-Studio/Signed_USB_Serial_Driver#3]
Hi, Even though it say signed - Windows does NOT allow me to install them.
I would be happy to have drivers for my boards to work with soon - OS Windows 8.1
Thanks.

**Comment by fmartingithub** [comment]
The same for me .. Any informations ? Thanks

**Comment by Cincinnatu** [comment]
I will be conducting tests soon, and if the issue persists, I will fix it.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
